function out1 = schwarchildIMetric(G,M,r,theta)
%SCHWARCHILDIMETRIC
%    OUT1 = SCHWARCHILDIMETRIC(G,M,R,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Mar-2020 23:24:46

%Inverse of the schwarchild metric
t2 = 1.0./r.^2;
t3 = G.*M.*2.0;
t4 = -t3;
t5 = r+t4;
out1 = reshape([-r./t5,0.0,0.0,0.0,0.0,t5./r,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,t2.*1.0./sin(theta).^2],[4,4]);
