function out1 = schwarchildIMetricDerv(G,M,r,theta)
%SCHWARCHILDIMETRICDERV
%    OUT1 = SCHWARCHILDIMETRICDERV(G,M,R,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Mar-2020 22:09:38

%Inverse derivative of the schwarchild metric
t2 = sin(theta);
t3 = 1.0./r.^3;
t4 = G.*M.*2.0;
t5 = -t4;
t6 = r+t5;
out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t4.*1.0./t6.^2,0.0,0.0,0.0,0.0,1.0./r.^4.*t4.*t6.^2.*1.0./(t4./r-1.0).^2,0.0,0.0,0.0,0.0,t3.*-2.0,0.0,0.0,0.0,0.0,1.0./t2.^2.*t3.*-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0./r.^2.*1.0./t2.^3.*cos(theta).*-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4,4]);
